### ISSUE TITLE
<Duda> Como buscar imagen el docker.uclv.cu

### ISSUE THREAD

**Issue by cz9dev** [linux8a/Docker-Cuba#6]
Hola me gustaría saber si docker uclv cuenta con la imagen ToolJet, en este caso es esta, pero en otro pudiera ser que necesitara otra imagen. Si alguien puede ayudarme les agradezco de antemanos

**Comment by linux8a** [comment]
Gusto en saludarle @cz9dev,

La universidad de las villas ( uclv ) tiene instalado un **[Sonatype Nexus](https://www.sonatype.com/products/sonatype-nexus-repository)** el cual es un administrador de repositorios que organiza, almacena y distribuye los artefactos necesarios para el desarrollo.  En el caso del registry [docker de uclv](docker.uclv.cu) es un proxy cache del registry de docker oficial. 

En resumen **_todo lo que esta en Docker Hub podrás descargarlo a través del registry docker de la uclv._**


La manera de buscar el nombre de la imagen es de esta forma:
 
`docker search docker.uclv.cu/[El nombre de la imagen que deseas buscar]`

Ejemplo de búsqueda usando el nombre de la imagen Tooljet:

```
docker search docker.uclv.cu/ToolJet
```

Saludos

**Comment by cz9dev** [comment]
Gracias por la pronta respuesta, cierro mi duda ya que con esto respondes a mi pregunta
